from mongoengine import Document, StringField, DecimalField


class Energy(Document):
    consumed_electricity_bought = DecimalField(null=True)
    natural_gas_bought = DecimalField(null=True)
    diesel_bought = DecimalField(null=True)
    fuel_oil_bought = DecimalField(null=True)
    nuclear_bought = DecimalField(null=True)
    coal_bought = DecimalField(null=True)
    wind_energy_bought = DecimalField(null=True)
    hidrelectric_bought = DecimalField(null=True)
    solar_bought = DecimalField(null=True)
    biomass_bought = DecimalField(null=True)
    biogas_bought = DecimalField(null=True)
    solid_waste_incineration_bought = DecimalField(null=True)
    consumed_electricity_produced = DecimalField(null=True)
    hidrelectric_produced = DecimalField(null=True)
    solar_produced = DecimalField(null=True)
    biomass_produced = DecimalField(null=True)
    biogas_produced = DecimalField(null=True)
    surplus_entered = DecimalField(null=True)
    pure_diesel_used_in_company = DecimalField(null=True)
    pure_gasoline_used_in_company = DecimalField(null=True)
    biofuel_used_in_company = DecimalField(null=True)
    lubricant_used_in_company = DecimalField(null=True)
    butane_used_in_company = DecimalField(null=True)
    propane_used_in_company = DecimalField(null=True)
    gpl_auto_used_in_company = DecimalField(null=True)
    natural_gas_used_in_company = DecimalField(null=True)
    biogas_used_in_company = DecimalField(null=True)
    wood_used_in_company = DecimalField(null=True)
    pellets_used_in_company = DecimalField(null=True)
    year = StringField(required=True)
    company_name = StringField(required=True)
